### ISSUE TITLE
[PROPOSAL] Probable copyright infringement of tolkien and dc comics

### ISSUE THREAD

**Issue by bartoszp1992** [ToyKeeper/anduril#117]
I have doubts about the use of the "Batt check" logo in the chart - it violates the intellectual property rights of DC comics.

It's similar with the name of the Andúril project.

Isn't it possible to change it somehow? Of course, I can fork it, but it would be nice if no one would pick on the author of the project when it gains even more popularity.
![Screenshot from 2024-11-15 09-44-19](https://github.com/user-attachments/assets/bf41afdb-e5a2-44eb-8c25-1376a8672940)

**Comment by SammysHP** [comment]
"Anduril" is not a problem, it's even the name of a big company (but this firmware came first). The use of the logo should also be fine in this context and type of use.

**Comment by bartoszp1992** [comment]
ChatGPT have doubts to that, and also on attached screen from tolkien estate, it can be problem. Also, if we are talking about it Anduril Industries are founded in 2017, and furst anduril UI commits are from 2022.

**Comment by DurvalMenezes** [comment]
> ChatGPT have doubts to that

Current AI engines, ChatGPT specially, are known to hallucinate (produce totally false answers, even as they're rethorically  convincing).

IANAL, but I think this project's use of the name "Anduril" falls squarely under the "Fair Use" exception to Copyright Law, at least in the US and other countries following this doctrine: https://en.m.wikipedia.org/wiki/Fair_use

**Comment by SammysHP** [comment]
> and furst anduril UI commits are from 2022.

No.

**Comment by bartoszp1992** [comment]
> > ChatGPT have doubts to that
> 
> Current AI engines, ChatGPT specially, are known to hallucinate (produce totally false answers, even as they're rethorically convincing).
> 
> IANAL, but I think this project's use of the name "Anduril" falls squarely under the "Fair Use" exception to Copyright Law, at least in the US and other countries following this doctrine: https://en.m.wikipedia.org/wiki/Fair_use

Okay, thanks. Seems legit.

**Comment by bartoszp1992** [comment]
> > and furst anduril UI commits are from 2022.
> 
> No.

Right, my mistake. I checked that only on github commits.

**Comment by ToyKeeper** [comment]
Copyright doesn't even apply to the name.  That's the realm of trademarks, and trademark law says this sort of thing is fine.  For more details on how that works, look up the case of Nissan Motors vs Nissan Computer.

As for the battcheck image, it may be covered by fair use, but that's something for courts to decide on a case by case basis.  It likely wouldn't even go to court though, because it's not worth paying a lawyer.  If DC cares, all they have to do is let me know and I'll change it, whether it's covered by fair use or not.  They don't seem to have a history of pursuing this sort of thing though, and they don't really have a reason to care anyway, since it's basically free advertising for them.

Given that GitHub currently has 13.4k repositories matching a search for the character that logo is for, and I can't find any instances of them attempting to strike that sort of thing, and the character's copyright expires in a few years anyway... I'm pretty sure there's no reason to worry.

Closing because no action is required.
